build: adjusting the result of the first pipeline

diff --git a/.github/workflows/first.yml b/.github/workflows/first.yml
--- a/.github/workflows/first.yml
+++ b/.github/workflows/first.yml
@@ -9,4 +9,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: First Job
-        run: exit 1
+        run: echo 'testing the first job'
+
+        # For testing failed
+        # run: exit 1
